//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class licences
    {
        public int id { get; set; }
        public Nullable<System.DateTime> licences_date { get; set; }
        public Nullable<System.DateTime> expire_date { get; set; }
        public Nullable<int> categorios { get; set; }
        public Nullable<int> licences_series { get; set; }
        public Nullable<int> licences_number { get; set; }
        public Nullable<int> driver_id { get; set; }
    
        public virtual Categorios Categorios1 { get; set; }
        public virtual Drivers Drivers { get; set; }
    }
}
