//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities6 : DbContext
    {
        public Entities6()
            : base("name=Entities6")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Categorios> Categorios { get; set; }
        public virtual DbSet<Drivers> Drivers { get; set; }
        public virtual DbSet<Fines> Fines { get; set; }
        public virtual DbSet<licences> licences { get; set; }
        public virtual DbSet<Region> Region { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Type_of_drive> Type_of_drive { get; set; }
        public virtual DbSet<Types_of_engine> Types_of_engine { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<vehides> vehides { get; set; }
    }
}
