//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class vehides
    {
        public int id { get; set; }
        public Nullable<int> VIN { get; set; }
        public Nullable<int> Manufacture { get; set; }
        public Nullable<int> Model { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> Weight { get; set; }
        public string Color { get; set; }
        public Nullable<int> Engine_Type { get; set; }
        public Nullable<int> type_of_drive { get; set; }
        public Nullable<int> driver_id { get; set; }
    
        public virtual Drivers Drivers { get; set; }
        public virtual Type_of_drive Type_of_drive1 { get; set; }
        public virtual Types_of_engine Types_of_engine { get; set; }
    }
}
